### ISSUE TITLE
each_extend and each_include are removed from rdoc 6.13.0 onwards

### ISSUE THREAD

**Issue by geiger-to** [BaseSecrete/rorvswild-theme-rdoc#3]
I ran into an issue while trying out this gem:

```
$ bundle exec rdoc --template rorvswild
Parsing sources...
100% [205/205] [redacted]

Generating Darkfish format into [redacted]

You can visit the home page at: [redacted]
uh-oh! RDoc had a problem:
error generating [redacted].html: Error while evaluating /[redacted]/ruby/3.4.1/lib/ruby/gems/3.4.0/gems/rorvswild_theme_rdoc-0.2/lib/rdoc/generator/template/rorvswild/class.rhtml: undefined method 'each_include' for an instance of RDoc::NormalModule (RDoc::Error)
```

It seems `each_extend` and `each_include` were removed in https://github.com/ruby/rdoc/pull/1315 and released in `6.13.0` (which I had installed locally).  Everything works fine when I dowgrade to rdoc `6.12.0`.

Assuming the maintainers of rdoc don't want to revert the change, the fix is replacing `each_include` and `each_extend` with `includes.each` and `extends.each` respectively . I'm happy to put up a two-line PR to fix this.

Thanks so much for your work on this theme. I'm a big fan!

cc @st0012

**Comment by st0012** [comment]
We're cleaning up RDoc's internal* to enable a few enhancements we want to make. And because RDoc doesn't have clear boundary for private/public API, especially for template generators, it'll inevitably break things. But in many cases these changes should be easy to adapt to. If that's not the case, we can work together to define better API like https://github.com/ruby/rdoc/pull/1330

**Comment by alexisbernard** [comment]
Thanks for the bug report. The PR is a bit more than 2 lines to keep it working with both 6.12 and 6.13. Probably the cleanest way is to have few classes or modules which monkey patch to handle all backward compatibilities.

@st0012, having an explicit public API would be great. Probably all methods called from the views by the official template are de facto public.

**Comment by alexisbernard** [comment]
I will try this way to handle any futur breaking change: https://github.com/BaseSecrete/rorvswild-theme-rdoc/compare/master...fix_compatibility_before_rdoc_6.13.0

**Comment by alexisbernard** [comment]
I have released the fix in version 0.3.0 :-)

@geiger-to, does the documentation have a public URL? Since I have no ideas of who using the theme, that would be nice if I could add a list in the README.

**Comment by geiger-to** [comment]
@alexisbernard thanks for publishing a fix. 

Although 6.13.0 removed `each_extend` and `each_include`, the corresponding `attr_readers` have been around for a long time now (at least 13 years by [this commit](https://github.com/ruby/rdoc/blob/504ed9e5eb563c22dbb4be87eea98e4a6b81ad5d/lib/rdoc/context.rb#L48-L56)). I don't think any monkey patching is necessary, since the readers already exist and `Rdoc::NormalClass`/`NormalModule` extends `Rdoc::Context`. I also tested this out on a local fork when I originally wrote the issue and the two-line fix worked as expected.

The `super_classes` patch _is_ necessary for users before 6.8.0, nice catch.

I'll share my usage of the theme soon—I am not quite ready to publish my project yet. Thanks again!

**Comment by alexisbernard** [comment]
Thanks for the feedback. I'm pretty sure I got an undefined method when I tested, but it seems I'm wrong 😅
